# Site settings
title: Debunk Central
description: Fact-checking viral videos and online claims
baseurl: ""
url: "https://yourdomain.com"
logo: "/assets/images/logo.png"

# SEO settings
twitter:
  username: debunkcentral
facebook:
  publisher: debunkcentral
social:
  name: Debunk Central
  links:
    - https://twitter.com/debunkcentral
    - https://facebook.com/debunkcentral

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Collections
collections:
  categories:
    output: true
    permalink: /category/:name/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      share: true